### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by iShortOne** [madchicken/homebridge-comelit-sb#5]
Hi, 
I have a problem loading the plugin, can you help me please? Thanks in advance!

22/9/2020, 18:13:23 Bridge is running on port 51826.
22/9/2020, 18:15:09 Got SIGINT, shutting down Bridge...
22/9/2020, 18:15:13 Loaded plugin "homebridge-comelit-sb-platform".
22/9/2020, 18:15:13 The requested platform "Comelit Serial Bridge" was not registered by any plugin.
22/9/2020, 18:15:13 Your config.json is requesting the platform "Comelit Serial Bridge" which has not been published by any installed plugins.
22/9/2020, 18:15:13 Bridge is running on port 51826.

"platforms": [
        {
            "platform": "Comelit Serial Bridge",
            "bridge_url": "http://192.168.1.xxx",
            "bridge_port": 80,
            "advanced": {
                "update_rate_sec": 5,
                "stop_blinds": false,
                "blind_closing_time": 35,
                "avoid_duplicates": true,
                "hide_lights": true,
                "hide_blinds": true,
                "hide_thermostats": false,
                "hide_dehumidifiers": false,
                "hide_power_suppliers": true,
                "hide_outlets": false
            }

**Comment by madchicken** [comment]
Sorry for my late response, I lost this issue: could you post start up homebridge logs? It's very important to understand what is causing the plugin crash

**Comment by madchicken** [comment]
@iShortOne any news on this issue?
