### ISSUE TITLE
Invert status option

### ISSUE THREAD

**Issue by ciapamusche** [madchicken/homebridge-comelit-sb#7]
Hi. Should be very useful have the possibility of choose the logic of status button. 
Some reseller install the outlet with inverted logic in order to keep the relay of the module not exited in normal mode. This cause an inverted rappresentation in state button.

If the plug-in user don't want to modify the electrical circuit of his home can have the possibility of invert this status by plugin?

Thank you

**Comment by madchicken** [comment]
Fixed in latest version (v2.3.0)
